name: microsoft_kiota_serialization_octet_stream
description: "Provides parsing and serialization support for the `application/octet-stream` content type."
version: 0.0.1
homepage: https://github.com/microsoft/kiota-dart/tree/main/packages/microsoft_kiota_serialization_octet_stream
repository: https://github.com/microsoft/kiota-dart

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  microsoft_kiota_abstractions:
    path: ../microsoft_kiota_abstractions
  typed_data: ^1.4.0
  uuid: ^4.5.1

dev_dependencies:
  strict: ^2.1.0
  test: ^1.25.14
