name: example
description: Shows how to use the microsoft_kiota_azure package.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  microsoft_kiota_azure:
    path: ../
  microsoft_kiota_bundle:
    path: ../../microsoft_kiota_bundle
