name: example
description: Shows how to use the microsoft_kiota_oauth package.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  oauth2: ^2.0.3
  microsoft_kiota_oauth:
    path: ../
  microsoft_kiota_bundle:
    path: ../../microsoft_kiota_bundle
