name: microsoft_kiota_http
description: "Provides an implementation of a Kiota RequestAdapter that uses `http`."
version: 0.0.7
homepage: https://github.com/microsoft/kiota-dart/tree/main/packages/microsoft_kiota_http
repository: https://github.com/microsoft/kiota-dart

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  microsoft_kiota_abstractions: ">=0.0.1 <0.9.0"
  http: ^1.2.2
  http_parser: ^4.0.2
  uuid: ^4.5.1

dev_dependencies:
  strict: ^2.1.0
  test: ^1.25.14
  mockito: ^5.4.5
  build_runner: any
