name: Dart

on:
  push:
    branches: [ "main" ]
    tags:
      - 'microsoft_kiota_abstractions-v*'
      - 'microsoft_kiota_bundle-v*'
      - 'microsoft_kiota_http-v*'
      - 'microsoft_kiota_oauth-v*'
      - 'microsoft_kiota_serialization_form-v*'
      - 'microsoft_kiota_serialization_json-v*'
      - 'microsoft_kiota_serialization_text-v*'
      - 'microsoft_kiota_serialization_multipart-v*'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    name: 'Discover packages'

    outputs:
      packages: ${{ steps.packages.outputs.packages }}

    steps:
      - uses: actions/checkout@v4

      - name: Discover packages
        id: packages
        run: |
          packages=$(ls -d packages/* | xargs -n 1 basename | jq -R -s -c 'split("\n")[:-1]')
          echo "packages=${packages}" >> $GITHUB_OUTPUT

  static-analysis:
    runs-on: ubuntu-latest
    needs: define-matrix

    permissions:
      checks: write

    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.define-matrix.outputs.packages) }}

    name: '${{ matrix.package }}: Static Analysis'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-pub

      - name: Install dependencies
        run: dart pub get
        working-directory: packages/${{ matrix.package }}

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
        working-directory: packages/${{ matrix.package }}

      - name: Prepare package
        if: always()
        run: dart run tooling prepare ${{ matrix.package }}
        working-directory: tooling

      - name: Analyze project source
        if: always()
        run: dart analyze --fatal-infos
        working-directory: packages/${{ matrix.package }}

  # Aggregates result of the static-analysis tests for use in branch policy
  check-static-analysis:
    runs-on: ubuntu-latest
    needs: static-analysis
    if: always()
    steps:
      - name: All build matrix options are successful
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: One or more build matrix options failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

  test:
    runs-on: ubuntu-latest
    needs: define-matrix

    strategy:
      matrix:
        package: ${{ fromJson(needs.define-matrix.outputs.packages) }}

    name: '${{ matrix.package }}: Test'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-pub

      - name: Install dependencies
        run: dart pub get
        working-directory: packages/${{ matrix.package }}

      - name: Prepare package
        run: dart run tooling prepare ${{ matrix.package }}
        working-directory: tooling

      - name: Run tests
        run: dart test
        working-directory: packages/${{ matrix.package }}


  # Aggregates result of the test tests for use in branch policy
  check-test:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: All build matrix options are successful
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: One or more build matrix options failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

  publish-dart:
    name: 'Publish packages'
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      id-token: write # Required for authentication using OIDC

    needs:
      - define-matrix

    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ${{ fromJson(needs.define-matrix.outputs.packages) }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-pub

      - name: Install dependencies
        run: dart pub get
        working-directory: packages/${{ matrix.package }}

      - name: Prepare package
        run: dart run tooling prepare ${{ matrix.package }}
        working-directory: tooling

      - name: Release dry run
        working-directory: packages/${{ matrix.package }}
        run: dart pub publish --dry-run

      # only push to pub.dev when a tag was created for that package
      - name: get package tag component
        id: get_tag_component
        run: |
            TAG_COMPONENT="refs/tags/${PACKAGE_NAME//-/_}-v"
            echo $TAG_COMPONENT
            echo "tag_component=$TAG_COMPONENT" >> $GITHUB_OUTPUT
        env:
            PACKAGE_NAME: ${{ matrix.package }}
      
      - name: Release to pub.dev
        if: startsWith(github.ref, steps.get_tag_component.outputs.tag_component)
        working-directory: packages/${{ matrix.package }}
        run: dart pub publish --force
      